-- Active: 1736185236225@@127.0.0.1@3306@photo_gallery_application
CREATE DATABASE photo_gallery_application

USE photo_gallery_application


CREATE TABLE photos(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(200),
    image_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


ALTER TABLE photos ADD description VARCHAR(255) NOT NULL AFTER title;

ALTER TABLE photos
MODIFY COLUMN image_path VARCHAR(250) NOT NULL;

ALTER TABLE photos
MODIFY COLUMN title VARCHAR(100) NOT NULL;
